### ISSUE TITLE
Enable EBS Snapshots

### ISSUE THREAD

**Issue by tarpanpathak** [d3sw/conductor#109]
As soon as data is populated in ElasticSearch, enable (hourly) snapshots on the following EBS volumes in `corp-test` and `corp-live`: 

conductor.search.test: **vol-0424e61729a51bf10** 
conductor.search.test: **vol-0b46950098fb1f2ba**
conductor.search.test: **vol-0ce0e364902753a8f**

conductor.search.live: **vol-01ed2e7bced985dc7**
conductor.search.live: **vol-067406e0deb8157c0**
conductor.search.live: **vol-0c7efd275247f29f7**

**Comment by ptarpan** [comment]
Hourly snapshots have been enabled on `conductor.search.test`. After testing/monitoring the performance of the DB, this process should be enabled on `conductor.search.live`.
